DEBUG = 1
USE_SLEPC = 0
CFLAGS_CUSTOM = -Wall -Wwrite-strings -g3
ifeq (${DEBUG}, 0)
	PETSC_ARCH = g64
else
	PETSC_ARCH = g64-debug
endif

PYTHON_INCLUDE_DIR = -I/usr/include/python2.7/
PYTHON_LIB_DIR = -L/usr/lib/python2.7/config
PYTHON_LIB = -lpython2.7 -lutil

include ${FD3D_ROOT}/src/makefiles/makefile_base
