# Copy this file to src/ directory, rename it to "makefile", and edit set the values of PETSC_ARCH as the PETSC_ARCH environment variables you used to install the PETSc library.
DEBUG = 0
CFLAGS_CUSTOM = -Wall -Wwrite-strings -g3
ifeq (${DEBUG}, 0)
	# PETSC_ARCH environment variable used to build PETSc library configured with "--with-debugging=0" flag
	PETSC_ARCH = petscfd3d
else
	# PETSC_ARCH environment variable used to build PETSc library configured with "--with-debugging=1" flag
	PETSC_ARCH =
endif

include ${FD3D_ROOT}/src/makefiles/makefile_base
